### ISSUE TITLE
Problem with download_model_checkpoint.sh

### ISSUE THREAD

**Issue by kobakos** [guglielmocamporese/hands-segmentation-pytorch#10]
Running main.py after running download_model_checkpoint.sh, results in an error message "_pickle.UnpicklingError: invalid load key, '<'. ".
It looks like the script is downloading the HTML file of a page that displays a warning that the file is too large to run a virus scan, instead of the actual model file.
Downloading the model file directly from the URL works as expected.

**Comment by akshay9396** [comment]
I got the same error. Did you solve it?

**Comment by guglielmocamporese** [comment]
Hi all,

Thanks for opening this issue. 
This problem should be fixed now - I just updated the script for downloading the model checkpoints, now it uses `gdown`.

Best,
Guglielmo
