### ISSUE TITLE
Model download problem

### ISSUE THREAD

**Issue by iiiicode** [guglielmocamporese/hands-segmentation-pytorch#3]
Hi. I downloaded it the way you did
# Download our pre-trained model
$ ./scripts/download_model_checkpoint.sh
Unable to download the file, could you please provide a link to Google cloud disk for me to download
thank you

**Comment by guoqiushi** [comment]
the same. It would be nice to provide a google cloud link for downloading the model

**Comment by guglielmocamporese** [comment]
Hi!

I just checked and tried to download the model - it is working on my end. Can you provide more details about the error you encounter?

In any case, this is the google drive link to the model: https://drive.google.com/file/d/1w7dztGAsPHD_fl_Kv_a8qHL4eW92rlQg/view?usp=sharing

Guglielmo

**Comment by guoqiushi** [comment]
Thanks for your reply. The google drive link works for me, can't help waiting to try your model!
