### ISSUE TITLE
What datasets are used for training?

### ISSUE THREAD

**Issue by fuyukaiKUN** [guglielmocamporese/hands-segmentation-pytorch#4]
Hello, I find your pretrained model really works on many cases. I wonder how the pretrained model provided in the torch hub is trainied? Specifically, what datasets are used? Do you use all the four datasets (EgoYouTubeHands, EgoHands, GTEA, HandOverFace) for training?

**Comment by guglielmocamporese** [comment]
Hi `fuyukaiKUN`,

thank you for your interest on my repo for hands segmentation, I'm happy that the model generalizes in many cases you have tried. Regarding your question - I trained the model using all datasets that are present in this repo, specifically I used `datasets="eyth eh hof gtea"` (as default) as input argument.

Hope this can help you,

Guglielmo
