### ISSUE TITLE
repo usage

### ISSUE THREAD

**Issue by hasibzunair** [guglielmocamporese/hands-segmentation-pytorch#6]
Hi, 

More of a comment than an issue! Used this repo in our winning solution (3rd place) accepted at CVPRW 2022, [arXiv](https://arxiv.org/abs/2204.11024) and [full paper](https://openaccess.thecvf.com/content/CVPR2022W/AICity/papers/Shihab_VISTA_Vision_Transformer_Enhanced_by_U-Net_and_Image_Colorfulness_Frame_CVPRW_2022_paper.pdf). We cited the repo in this way. 

```
Guglielmo Camporese. Hands Segmentation in PyTorch - A Plug and Play Model, 2021. Available at https://github.com/guglielmocamporese/hands-segmentation-pytorch.
```

Consider adding them in the repo. Thanks!

**Comment by guglielmocamporese** [comment]
Great! 

I was in New Orleans at CVPR 2022 too :) . I have a paper at the "Transformers 4 Vision" workshop (here my oral spotlight [paper](https://arxiv.org/abs/2206.00481)). 

Thank you for citing the repo, I'll add your paper reference to the readme file.

**Comment by hasibzunair** [comment]
Awesome! Thanks for adding our paper. :D
